// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.example.tutorial;

/**
 * Protobuf enum {@code EnumAllowingAlias}
 */
public enum EnumAllowingAlias
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>UNKNOWN = 0;</code>
   */
  UNKNOWN(0),
  /**
   * <code>STARTED = 1;</code>
   */
  STARTED(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>RUNNING = 1;</code>
   */
  public static final EnumAllowingAlias RUNNING = STARTED;
  /**
   * <code>UNKNOWN = 0;</code>
   */
  public static final int UNKNOWN_VALUE = 0;
  /**
   * <code>STARTED = 1;</code>
   */
  public static final int STARTED_VALUE = 1;
  /**
   * <code>RUNNING = 1;</code>
   */
  public static final int RUNNING_VALUE = 1;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EnumAllowingAlias valueOf(int value) {
    return forNumber(value);
  }

  public static EnumAllowingAlias forNumber(int value) {
    switch (value) {
      case 0: return UNKNOWN;
      case 1: return STARTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EnumAllowingAlias>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EnumAllowingAlias> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EnumAllowingAlias>() {
          public EnumAllowingAlias findValueByNumber(int number) {
            return EnumAllowingAlias.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.example.tutorial.OuterSample.getDescriptor()
        .getEnumTypes().get(0);
  }

  private static final EnumAllowingAlias[] VALUES = {
    UNKNOWN, STARTED, RUNNING, 
  };

  public static EnumAllowingAlias valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private EnumAllowingAlias(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:EnumAllowingAlias)
}

