// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.example.tutorial;

public interface MsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Msg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string foo = 1;</code>
   */
  java.lang.String getFoo();
  /**
   * <code>optional string foo = 1;</code>
   */
  com.google.protobuf.ByteString
      getFooBytes();

  /**
   * <code>optional .SecondMsg blah = 2;</code>
   */
  boolean hasBlah();
  /**
   * <code>optional .SecondMsg blah = 2;</code>
   */
  com.example.tutorial.SecondMsg getBlah();
  /**
   * <code>optional .SecondMsg blah = 2;</code>
   */
  com.example.tutorial.SecondMsgOrBuilder getBlahOrBuilder();
}
