// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.example.tutorial;

public final class OuterSample {
  private OuterSample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Msg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Msg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Family_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Family_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Family_Key2PEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Family_Key2PEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SecondMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SecondMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014sample.proto\",\n\003Msg\022\013\n\003foo\030\001 \001(\t\022\030\n\004bl" +
      "ah\030\002 \001(\0132\n.SecondMsg\".\n\006Person\022\013\n\003age\030\001 " +
      "\001(\005\022\r\n\005names\030\002 \003(\tR\003fooR\003bar\"{\n\006Family\022\027" +
      "\n\006person\030\001 \003(\0132\007.Person\022!\n\005key2P\030\002 \003(\0132\022" +
      ".Family.Key2PEntry\0325\n\nKey2PEntry\022\013\n\003key\030" +
      "\001 \001(\t\022\026\n\005value\030\002 \001(\0132\007.Person:\0028\001\"(\n\tSec" +
      "ondMsg\022\014\n\004blah\030\001 \001(\005\022\r\n\005names\030\002 \003(\t*>\n\021E" +
      "numAllowingAlias\022\013\n\007UNKNOWN\020\000\022\013\n\007STARTED" +
      "\020\001\022\013\n\007RUNNING\020\001\032\002\020\001B%\n\024com.example.tutor" +
      "ialB\013OuterSampleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Msg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Msg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Msg_descriptor,
        new java.lang.String[] { "Foo", "Blah", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Age", "Names", });
    internal_static_Family_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Family_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Family_descriptor,
        new java.lang.String[] { "Person", "Key2P", });
    internal_static_Family_Key2PEntry_descriptor =
      internal_static_Family_descriptor.getNestedTypes().get(0);
    internal_static_Family_Key2PEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Family_Key2PEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_SecondMsg_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SecondMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SecondMsg_descriptor,
        new java.lang.String[] { "Blah", "Names", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
