// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sample.proto

package com.example.tutorial;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int32 age = 1;</code>
   */
  int getAge();

  /**
   * <code>repeated string names = 2;</code>
   */
  java.util.List<java.lang.String>
      getNamesList();
  /**
   * <code>repeated string names = 2;</code>
   */
  int getNamesCount();
  /**
   * <code>repeated string names = 2;</code>
   */
  java.lang.String getNames(int index);
  /**
   * <code>repeated string names = 2;</code>
   */
  com.google.protobuf.ByteString
      getNamesBytes(int index);
}
