/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.greenleaf.erp.api;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
public class ErpConstants {

  public static final int MATHPATH = 256;

}
